spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oficina
    username: root
  jpa:
    openInView: true
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    showSql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 70MB
  output:
    ansi:
      enabled: ALWAYS

server:
  error:
    include-stacktrace: NEVER

file:
  upload-dir: ./res/produtos

logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: warn
