spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oficina
    username: root
  jpa:
    openInView: true
    hibernate:
      ddlAuto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    showSql: false
  output:
    ansi:
      enabled: ALWAYS
server:
  error:
    include-stacktrace: NEVER

logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: warn
